/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.vmware.vchs.load.generator.service;

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum MyTimeUnit implements org.apache.thrift.TEnum {
    MILLISECOND(0), SECOND(1), MINUTE(2), HOUR(3);

    private final int value;

    private MyTimeUnit(int value) {
        this.value = value;
    }

    /**
     * Get the integer value of this enum value, as defined in the Thrift IDL.
     */
    public int getValue() {
        return value;
    }

    /**
     * Find a the enum type by its integer value, as defined in the Thrift IDL.
     * 
     * @return null if the value is not found.
     */
    public static MyTimeUnit findByValue(int value) {
        switch (value) {
        case 0:
            return MILLISECOND;
        case 1:
            return SECOND;
        case 2:
            return MINUTE;
        case 3:
            return HOUR;
        default:
            return null;
        }
    }
}
