import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'liuda' at '7/30/15 6:33 AM' with Gradle 2.4
 *
 * @author liuda, @date 7/30/15 6:33 AM
 */
public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
    }
}
